### ISSUE TITLE
clarify requirements for link length

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#27]
Currently, a link object has an optional `length` property.  Should this be a clear recommendation in the specification?

Related: we could consider HTTP HEAD requests (i.e. `Content-Length`) to determine data size apriori.

cc @kaiwirt @golfvert @josusky @antje-s

**Comment by josusky** [comment]
The HEAD request is a standard HTTP feature implemented in all web servers but I am afraid that the size is not known in advance in the case of services that do not serve "static" content/files and such services may not be able to answer HEAD requests either. So we may kindly ask for (recommend) reliable HEAD request implementation but we cannot mandate it. On the other hand, if the data gets to the Global Chache the size is known so the cache "shall" send notifications with the correctly filled `length` value. Sorry @kaiwirt and @antje-s

**Comment by kaiwirt** [comment]
In my opinion it would be easier to have a field in the message instead of using an HTTP HEAD request. Using HTTP HEAD is a media change in my opinion. Moving from processing the message, then downloading the file to processing the message, then evaluating HTTP HEAD, then downloading. Currently i don't like adding that extra step.

I agree with @josusky that if the originator can not add a size field to the message, it is likely that the size will not be available in the Header as well.

Maybe a good compromise would be to make it a strong requirement, but not a must. A user or cache might then decide if they are going to download data that is missing the size attribute.

**Comment by tomkralidis** [comment]
Thanks. Will add as a recommendation (SHOULD).
