### ISSUE TITLE
clarify properties.integrity mandatory or optional

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#28]
(carryon from #26 from @antje-s)

7.1.7.4. Integrity --> Should be changed to "SHALL" (and required under https://github.com/wmo-im/wis2-notification-message/blob/main/WIS2_Message_Format_Schema.yaml ) : otherwise no verification of the download is possible if it is not included

cc @kaiwirt @josusky @golfvert

**Comment by kaiwirt** [comment]
+1 for mandatory.

Need to also consider if verification is mandatory or optional. See also #19

**Comment by josusky** [comment]
I am not sure if I should mention it here or create a separate issue, but the encoding for the integrity value is not specified. The example seems like a hexadecimal number but it is not explicitly stated. BTW, in `v03` this field used base64 encoding.

**Comment by kaiwirt** [comment]
I am happy with the ASCII representation of the hex value as it is in v04.

This conforms to what command line tools like sha256sum output.

**Comment by kaiwirt** [comment]
Second thought: We have the discussion that the data size can not be calculated for services here: #27 
The same is true for integrity. If data is provided through a WebService it might not be possible to calculate the integrity value. So in this case i would suggest to make integrity a strong requirement, but no must.

**Comment by tomkralidis** [comment]
Thanks @kaiwirt. Updated SHOULD statement in recommendations.

**Comment by josusky** [comment]
I agree that integrity shall be optional or nullable because there are services that do have the data ready in advance.
When it concerns the encoding for the integrity/hash value, @kaiwirt I agree that for some testing purposes it is useful to be able to use CLI tools to generate a hash but there are ways how to convert it, e.g. like this `sha256sum test.data | xxd -r -p | base64`. For the reverse conversion, you can use `echo "<base64-value>" | base64 -d | hexdump -e '"%02X"'`  However, for day-to-day operations, we will all use higher-level tools not just `bash` :-)
Any decent programming language has a base64 encoding/decoding functionality, in fact, we already use base64 encoding for the "content" field. So we are not adding an additional dependency here. To sum it up, pros of base64 for integrity value:
# One way of encoding all (both) binary data fields in the notification.
# Shorter.
# Backward compatible with `v03`.
Cons:
# Less comfortable for CLI.

**Comment by kaiwirt** [comment]
I made a sperate issue on the encoding of the hash value: #39
