### ISSUE TITLE
add event types to message

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-notification-message#47]
@wmo-im/tt-wismd 

We should consider adding a "event type" level, for users to be able to subscribe to update/delete workflows, i.e.:

event-type: `created|updated|deleted`

cc @cmheazel following discussions in OGC.

**Comment by tomkralidis** [comment]
PR in #48

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-22: add to normative text on the granularity of when to use `properties.operation`:
- qualify delete operation
  - can be used for metadata, or special cases of delete (archive data)
  - SHOULD NOT be used for high frequency momentum data (superfluous/chatty)
  - ACTION: need a new issue for updates

**Comment by josusky** [comment]
BTW, could we change the values to `create`, `update`, and `delete`? I mean, as it is the name of an operation, this seems to be a better fit than `created` etc., or is it just my poor knowledge of English that confuses me?

**Comment by tomkralidis** [comment]
Yes, the PR in #48 implements as verbs.

**Comment by antje-s** [comment]
Wondering if this additional event type field is still needed. If we use data_id&pubtime for decision whether data is already downloaded the latest publish will always update previous versions (if filename not changed in link).  Deletion would be possible via new notification with original filename extended with e.g. "_deleted" included in canonical link and an empty file.

**Comment by tomkralidis** [comment]
Good points @antje-s.  Perhaps, given `data_id`&`pubtime`, we can put forth the following link representation for deletions:

```json
{
    "type": "deleted",
    "href": null
}
```

However this would break schema validation because `href` needs to be a string.  Perhaps `"href": "about:blank"` as a "null URL" (which we would document).  So:

```json
{
    "type": "deleted",
    "href": "about:blank"
}
```


Thoughts?  This would result in no new elements and reusing the semantics of data_id+pubtime.

**Comment by antje-s** [comment]
Using "about:blank" as href value may lead to less flexibility, since we can always find the file via data-id for metadata, but for data files (at least currently) the data-id does not have to be included in either the filename or the content, so mapping without the original href-link filename may cause problems. The original href-link extended by suffix e.g. "_deleted" would be sufficient from my point of view. With a fixed suffix the file size would not be relevant, but the name would be relevant for deleting, This would avoid problems when accidentally empty files are deposited as link source. The additional field "type" with value "deleted" is not needed in this case.
Alternatively we can make the inclusion of the data-id in the filename mandatory - but that results in longer filenames.

**Comment by josusky** [comment]
@tomkralidis , do I understand you right, that you are proposing to notify about deletion of a resource by sending a notification that will have all usual parameters (including `metadata_id` if applicable), just the link will contain "empty" `href` and `type` set to `delete(d)`?

**Comment by tomkralidis** [comment]
@josusky yes.  We would probably need to think the link relation through a bit more (i.e. `resource-deletion`, etc.), but using a custom link relation with a "null" URL `about:blank` along with what we already have might work.

**Comment by 6a6d74** [comment]
How about … 
`href:”#”`

**Comment by tomkralidis** [comment]
That could work as well.

Adding another dimension RE: tooling and URL validity:

```bash
$ curl "#"
curl: (3) URL using bad/illegal format or missing URL
$ curl ""
curl: (3) URL using bad/illegal format or missing URL
$ curl file://
curl: (3) URL using bad/illegal format or missing URL
$ curl file:///
curl: (37) Couldn't open file /
$ curl "about:blank"
curl: (3) URL using bad/illegal format or missing URL
```

More options:
1. make `links` optional, with the behaviour that if there is no `links` array, then the message implies a deletion
2. set the same link for a deletion per:

```json
{
    "rel": "deletion",
    "href": "https://example.org/msc-swob-station123-obs-202308231113.geojson"
}
```

with the implication that `rel=deletion` means the resource is deleted.  The `href` is then valid and will respond with a 404.  Hence a WIS2 aware broker client would not fetch the `href` given `rel=deletion`.  A non-aware client would reach a 404 (or a 410).

**Comment by kaiwirt** [comment]
My thoughts on this:

- I would like to have an explicit value in the WNM telling me, what to do (update, delete, create). I would rather not rely on a combination of other keys to figure that out
- As i stated in https://github.com/wmo-im/wis2-notification-message/issues/50 to me pubtime can be used to determine if i already have that update or if this WNM is about the newest version. Given, that an event type told me that this is an update.
- In case of delete I would either go for an empty link (something like file:/// or http:///) or reuse the link to the file that i want deleted. Mainly, because we said that the option to download the data by following the link is a MUST and as such i would consider the link property mandatory.

**Comment by amilan17** [comment]
note that there is an section in the guide that may need to be updated: https://github.com/wmo-im/wis2-guide/blob/transition/Notification-mechanism-updated-data.adoc
